services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks: 
      - default
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
      # game:
      #   condition: service_healthy

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "9000"
    environment:
      - APP_KEY=${APP_KEY}
    networks: 
      - default

  frontend:
    build: ./frontend
    container_name: frontend
    expose: 
      - "3000"
    networks:
      - default

  # game:
  #   build: ./game
  #   container_name: game
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "5000:5000"
  #   networks: 
  #     - default
    
networks:
  default:
    name: net-transcendence
    driver: bridge
