services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - default
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules # excluye la carpeta /node_modules de reemplazar la carpeta del mismo nombre dentro del contenedor. Para que use el directorio que ya se ha generado dentro del contenedor -> Las dependencias del contenedor y de la maquina host no son los mismos
    expose:
      - "9000"
    ports:
      - "9000:9000" #Eliminar esta linea en produccion, esto me deja conectarme desde fuera del doker
    environment:
      - APP_KEY=${APP_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"] # curl -f (o --fail) hace que curl devuelva un código de salida distinto de cero si el servidor responde con un error HTTP (4xx o 5xx)
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 30s
    networks:
      - default

  frontend:
      build: ./frontend
      container_name: frontend
      volumes:
        - ./frontend:/app
        - /app/node_modules # crea un volumén gestionado por docker dónde se almacena el cotenido de /app/node_modules -> así el contenedor no tiene que hacer 'npm install' cada vez que levantamos los contenedores
      expose:
        - "3000"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"]
        interval: 30s
        timeout: 10s
        retries: 1
        start_period: 30s
      networks:
        - default

networks:
  default:
    name: net-transcendence
    driver: bridge
